//
// Created by Joe Wu on 2022/4/9.
//

#ifndef ALGORITHM_C_PRIORITYQUEUEBYINTARRAY_H
#define ALGORITHM_C_PRIORITYQUEUEBYINTARRAY_H

void doPriorityQueue();

#endif //ALGORITHM_C_PRIORITYQUEUEBYINTARRAY_H
